### ISSUE TITLE
Clipboard Copies Ansi Escapes when using $PSStyle.OutputRendering = 'PlainText'

### ISSUE THREAD

**Issue by ninmonkey** [SeeminglyScience/ClassExplorer#47]
## Summary

- Ansi Escapes are copied to the clipboard when using `OutputRendering = 'PlainText'`. 
- Ansi Escapes are preserved in a round-trip with `PlainText` Mode

## To Reproduce

```ps1
$PSStyle.OutputRendering = 'PlainText'
# breaks
[uri] | Find-Member *escape* | % DisplayString | Set-Clipboard

# I thought maybe round trip would omit escapes, but it copies them
# breaks:
[uri] | Find-Member *escape* | % DisplayString
| Set-Clipboard | Get-Clipboard | Set-Clipboard

# works:
[uri] | Find-Member *escape* | % DisplayString
| Set-Clipboard | Get-Clipboard
```

![image](https://user-images.githubusercontent.com/3892031/168401066-22646d37-54ae-4caf-849e-e327b3026ee0.png)

## Working cases

It seems like other cases are reverting to plain-text, it's specifically the clipboard call.

![image](https://user-images.githubusercontent.com/3892031/168401071-87da3b6d-f3bc-4f9e-9ef8-6d335310014e.png)

```ps
[uri] | Find-Member *escape* | % DisplayString | out-string | Set-Clipboard

7.2.3🐒> $x # also clean
7.2.3🐒> $x = [uri] | Find-Member *escape* | % DisplayString
public static string UnescapeDataString(string stringToUnescape);
public static string EscapeUriString(string stringToEscape);
public static string EscapeDataString(string stringToEscape);
public static string HexEscape(char character);
public static char HexUnescape(string pattern, ref int index);
public bool UserEscaped { get; }
```

## Environment

![image](https://user-images.githubusercontent.com/3892031/168401502-55954cc8-6896-4837-b09d-97c798019aa8.png)
```yml
chocolateyProfile: 0.0
ClassExplorer: 2.3.3
Configuration: 1.3.1
dev.nin: 0.0.17
functional: 0.0.4
ninmonkey.console: 0.2.7
Pansies: 2.3.1
pslambda: 0.2.0
PSReadLine: 2.2.0
Utility: 0.0
```
